# Generated by Django 5.2.7 on 2025-10-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_path',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='post/images'),
        ),
    ]
