# Generated by Django 5.2.7 on 2025-10-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_image_path_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='color',
            new_name='bg_color',
        ),
        migrations.AddField(
            model_name='tag',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
