# Generated by Django 5.2.8 on 2025-11-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postimage',
            unique_together={('order', 'post')},
        ),
    ]
