# Generated by Django 5.2.6 on 2025-11-19 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_postimage_unique_together'),
        ('posts', '0009_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
    ]
